---
- name: Report concurrency exceeded
  debug:
    msg: >-
      Maximum concurrency of {{ maximum_job_count }} exceeded.
      {{ active_job_count }} active jobs.
      Will try to again in {{ job_check_interval }}.
