---
- name: Get secret for {{ job_info.towerHost }}
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ anarchy_namespace }}"
    label_selectors:
    - babylon.gpte.redhat.com/ansible-control-plane={{ job_info.towerHost }}
  register: r_get_secret
  failed_when: r_get_secret.resources | length < 1

- name: Attempt login to {{ job_info.towerHost }}
  vars:
    __secret: "{{ r_get_secret.resources[0] }}"
    __user: "{{ __secret.data.user | b64decode | from_yaml }}"
    __password: "{{ __secret.data.password | b64decode | from_yaml }}"
  awx.awx.token:
    scope: write
    controller_host: "https://{{ job_info.towerHost }}/"
    controller_username: "{{ __user }}"
    controller_password: "{{ __password }}"
  register: r_get_token

- name: Set controller
  vars:
    __secret: "{{ r_get_secret.resources[0] }}"
  set_fact:
    controller:
      hostname: "{{ job_info.towerHost }}"
      oauthtoken: "{{ r_get_token.ansible_facts.controller_token }}"

- name: Report controller
  debug:
    msg:
    - "controller hostname: {{ controller.hostname }}"
...
