---

- name: Cancel tower jobs for {{ anarchy_subject_name }}
  loop: >-
    {{ vars.anarchy_subject.status.TowerJobs | default({}) | dict2items
     | json_query('[?value.deployerJob && value.completeTimestamp==null]')
    }}
  loop_control:
    label: "{{ __job.key }}"
    loop_var: __job
  vars:
    job_info: "{{ __job.value }}"
  include_tasks:
    file: cancel-job.yaml

- name: Handle delete without destroy
  when: >-
    vars.anarchy_subject.status.towerJobs.provision.deployerJob | default('') == '' or
    deployer_entry_points.destroy | default('', true) == '' or
    'destroy' not in vars.anarchy_governor.spec.actions
  include_tasks: handle-event-delete-no-destroy.yaml

- name: Handle delete with destroy
  when: >-
    vars.anarchy_subject.status.towerJobs.provision.deployerJob | default('') != '' and
    deployer_entry_points.destroy | default('', true) != '' and
    'destroy' in vars.anarchy_governor.spec.actions
  include_tasks: handle-event-delete-with-destroy.yaml
...
