---
- name: Set current state to destroy-failed for {{ anarchy_subject_name }}
  anarchy_subject_update:
    skip_update_processing: true
    metadata:
      labels:
        state: destroy-failed
    spec:
      vars:
        current_state: destroy-failed
    status:
      towerJobs:
        destroy:
          completeTimestamp: '{{ anarchy_run_timestamp }}'
          jobStatus: failed

- name: Schedule destroy retry for {{ anarchy_subject_name }}
  anarchy_continue_action:
    after: "{{ action_retry_interval }}"
    vars: "{{ {'action_retry_count': 1 + action_retry_count | int} }}"
...
