---

- name: Cancel tower jobs for {{ anarchy_subject_name }}
  loop: >-
    {{ vars.anarchy_subject.status.TowerJobs | default({}) | dict2items
     | json_query('[?value.deployerJob && value.completeTimestamp==null]')
    }}
  loop_control:
    label: "{{ __job.key }}"
    loop_var: __job
  vars:
    job_info: "{{ __job.value }}"
  include_tasks:
    file: cancel-job.yaml

- name: Immediately remove finalizers on {{ anarchy_subject_name }} if never provisioned or destroy not configured
  when: >-
    vars.anarchy_subject.status.towerJobs.provision.deployerJob | default('') == '' or
    deployer_entry_points.destroy | default('', true) == '' or
    'destroy' not in vars.anarchy_governor.spec.actions
  anarchy_subject_delete:
    remove_finalizers: true

- name: Schedule destroy {{ anarchy_subject_name }}
  when: >-
    vars.anarchy_subject.status.towerJobs.provision.deployerJob | default('') != '' and
    deployer_entry_points.destroy | default('', true) != '' and
    'destroy' in vars.anarchy_governor.spec.actions
  anarchy_schedule_action:
    action: destroy
    cancel:
    - start
    - stop
    - update
...
