---
- name: Set current state to start-failed for {{ anarchy_subject_name }}
  anarchy_subject_update:
    skip_update_processing: true
    metadata:
      labels:
        state: start-failed
    spec:
      vars:
        current_state: start-failed
        healthy: false

- name: Schedule start retry for {{ anarchy_subject_name }}
  when: desired_state == 'started' and anarchy_subject.metadata.deletionTimestamp is not defined
  anarchy_continue_action:
    after: "{{ action_retry_interval }}"
    vars: "{{ {'action_retry_count': 1 + action_retry_count | int} }}"

- name: Schedule stop after start failed for {{ anarchy_subject_name }}
  when: desired_state == 'stopped' and anarchy_subject.metadata.deletionTimestamp is not defined
  anarchy_schedule_action:
    action: stop
    cancel:
    - start
    - stop

- name: Finish action {{ anarchy_action_name }} as failed
  when: desired_state != 'started' or anarchy_subject.metadata.deletionTimestamp is defined
  anarchy_finish_action:
    state: failed
...
