---
- name: Set status data and messages for {{ anarchy_subject_name }}
  anarchy_subject_update:
    spec:
      vars:
        check_status_state: successful
        status_data: '{{ action_provision_data | default(omit, true) }}'
        status_messages: '{{ action_provision_messages | default(omit, true) }}'
    status:
      towerJobs:
        status:
          completeTimestamp: '{{ anarchy_run_timestamp }}'
          jobStatus: complete

- name: Report action successful
  anarchy_finish_action:
    state: successful
...
