---
- name: Schedule destroy {{ anarchy_subject_name }}
  anarchy_schedule_action:
    action: destroy
    cancel:
    - start
    - stop
    - update

- name: Update desired_state to destroyed for {{ anarchy_subject_name }}
  anarchy_subject_update:
    spec:
      vars:
        current_state: destroy-pending
        desired_state: destroyed
...
