---
- name: Set state started for {{ anarchy_subject_name }}
  anarchy_subject_update:
    metadata:
      labels:
        state: started
    spec:
      vars:
        current_state: started
        healthy: true
        provision_data: '{{ action_provision_data | default(omit, true) }}'
        provision_message_body: '{{ action_provision_message_body | default(omit, true) }}'
        provision_messages: '{{ action_provision_messages | default(omit, true) }}'
    status:
      actions:
        provision:
          completeTimestamp: '{{ now_time_utc }}'
          state: successful
      towerJobs:
        provision:
          completeTimestamp: '{{ now_time_utc }}'
          jobStatus: successful

- name: Report action successful
  anarchy_finish_action:
    state: successful
...
