---
- when: sandbox_api_in_use | bool
  include_tasks: sandbox_cleanup.yml

- name: Set state destroy for {{ anarchy_subject_name }}
  anarchy_subject_update:
    skip_update_processing: true
    metadata:
      labels:
        state: destroy-complete
    spec:
      vars:
        current_state: destroy-complete
    status:
      actions:
        destroy:
          completeTimestamp: '{{ now_time_utc }}'
          state: successful
      towerJobs:
        destroy:
          completeTimestamp: '{{ now_time_utc }}'
          jobStatus: successful

- name: Complete AnarchySubject deletion
  anarchy_subject_delete:
    remove_finalizers: true
...
