---
- name: Set state started for {{ anarchy_subject_name }}
  anarchy_subject_update:
    metadata:
      labels:
        state: started
    spec:
      vars:
        current_state: started
        healthy: true
        provision_data: '{{ action_provision_data | default(omit, true) }}'
        provision_message_body: '{{ action_provision_message_body | default(omit, true) }}'
        provision_messages: '{{ action_provision_messages | default(omit, true) }}'
    status:
      towerJobs:
        provision:
          completeTimestamp: '{{ anarchy_run_timestamp }}'

- name: Cancel provision check
  anarchy_schedule_action:
    cancel: ['check']

- when: schedule_stop_after_provision != 'disabled'
  name: Schedule stop {{ anarchy_subject_name }} after {{ schedule_stop_after_provision }}
  anarchy_schedule_action:
    action: stop
    after: "{{ schedule_stop_after_provision }}"

- when: schedule_destroy_after_provision != 'disabled'
  name: Schedule stop {{ anarchy_subject_name }} after {{ schedule_destroy_after_provision }}
  anarchy_schedule_action:
    action: destroy
    after: "{{ schedule_destroy_after_provision }}"

- name: Report action successful
  anarchy_finish_action:
    state: successful
...
