---
- name: Set state stopped for {{ anarchy_subject_name }}
  anarchy_subject_update:
    status:
      actions:
        stop:
          completeTimestamp: '{{ now_time_utc }}'
          state: successful
      towerJobs:
        stop:
          completeTimestamp: '{{ now_time_utc }}'
          jobStatus: successful

- when: >-
    sandbox_api_in_use | bool
    and __meta__.sandbox_api.actions.stop.enable | default(true) | bool
  block:
  - include_tasks: sandbox_api_login.yaml
  - include_tasks: sandbox_api_stop.yaml

- name: Set state stopped for {{ anarchy_subject_name }}
  anarchy_subject_update:
    metadata:
      labels:
        state: stopped
    spec:
      vars:
        current_state: stopped

- name: Report action successful
  anarchy_finish_action:
    state: successful
...
