---
- name: Destroying {{ anarchy_subject_name }}
  when: current_state != "destroying"
  include_tasks: run-destroy.yaml

- name: Check destroy of {{ anarchy_subject_name }}
  when: current_state == "destroying"
  vars:
    job_action: destroy
    job_info: "{{ vars.anarchy_subject.status.towerJobs.destroy }}"
  include_tasks: check-deployer-job.yaml
...
