---
- name: Set current state to update-canceled for {{ anarchy_subject_name }}
  anarchy_subject_update:
    skip_update_processing: true
    metadata:
      labels:
        state: update-canceled
    spec:
      vars:
        current_state: update-canceled
        healthy: false

- name: Schedule update retry for {{ anarchy_subject_name }}
  when: anarchy_subject.metadata.deletionTimestamp is not defined
  anarchy_continue_action:
    after: "{{ action_retry_intervals[0] }}"

- name: Finish action {{ anarchy_action_name }} as canceled
  when: anarchy_subject.metadata.deletionTimestamp is defined
  anarchy_finish_action:
    state: canceled
...
