---
- name: Set state started for {{ anarchy_subject_name }}
  anarchy_subject_update:
    metadata:
      labels:
        state: started
    spec:
      vars:
        current_state: started
    status:
      actions:
        start:
          completeTimestamp: '{{ now_time_utc }}'
          state: successful
      towerJobs:
        start:
          completeTimestamp: '{{ now_time_utc }}'
          jobStatus: successful

- name: Report action successful
  anarchy_finish_action:
    state: successful
...
