---
- name: Set state started for {{ anarchy_subject_name }}
  anarchy_subject_update:
    metadata:
      labels:
        state: started
    spec:
      vars:
        current_state: started
        healthy: true
        provision_data: '{{ action_provision_data | default(omit, true) }}'
        provision_message_body: '{{ action_provision_message_body | default(omit, true) }}'
        provision_messages: '{{ action_provision_messages | default(omit, true) }}'
    status:
      towerJobs:
        provision:
          completeTimestamp: '{{ anarchy_run_timestamp }}'

- name: Cancel provision check
  anarchy_schedule_action:
    cancel: ['check']

- name: Report action successful
  anarchy_finish_action:
    state: successful
...
