---
- name: Set failure check_status_state for {{ anarchy_subject_name }}
  when: job_action == 'status'
  anarchy_subject_update:
    skip_update_processing: true
    spec:
      vars:
        check_status_state: canceled
    status:
      actions:
        status:
          completeTimestamp: '{{ anarchy_run_timestamp }}'
          state: canceled
      towerJobs:
        status:
          completeTimestamp: '{{ anarchy_run_timestamp }}'
          jobStatus: canceled

- name: Finish action {{ anarchy_action_name }} as canceled
  anarchy_finish_action:
    state: failed
...
