---
- when: sandbox_api_in_use | bool and 'aws' in sandbox_api_providers
  include_tasks: aws_sandbox_cleanup.yml

- name: Set state destroy for {{ anarchy_subject_name }}
  anarchy_subject_update:
    skip_update_processing: true
    metadata:
      labels:
        state: destroy-complete
    spec:
      vars:
        current_state: destroy-complete
    status:
      towerJobs:
        destroy:
          completeTimestamp: '{{ anarchy_run_timestamp }}'
          jobStatus: successful

- name: Complete AnarchySubject deletion
  anarchy_subject_delete:
    remove_finalizers: true
...
