---
- name: Set current state to start-canceled for {{ anarchy_subject_name }}
  anarchy_subject_update:
    skip_update_processing: true
    metadata:
      labels:
        state: start-canceled
    spec:
      vars:
        current_state: start-canceled
        healthy: false
    status:
      actions:
        start:
          completeTimestamp: '{{ now_time_utc }}'
          state: canceled
      towerJobs:
        start:
          completeTimestamp: '{{ now_time_utc }}'
          jobStatus: canceled

- name: Schedule start retry for {{ anarchy_subject_name }}
  when: desired_state == 'started' and vars.anarchy_subject.metadata.deletionTimestamp is not defined
  anarchy_continue_action:
    after: "{{ action_retry_intervals[0] }}"

- name: Schedule stop after start canceled for {{ anarchy_subject_name }}
  when: desired_state == 'stopped' and vars.anarchy_subject.metadata.deletionTimestamp is not defined
  anarchy_schedule_action:
    action: stop
    cancel:
    - start
    - stop

- name: Finish action {{ anarchy_action_name }} as canceled
  when: desired_state != 'started' or vars.anarchy_subject.metadata.deletionTimestamp is defined
  anarchy_finish_action:
    state: canceled
...
