---
- name: Set state updated for {{ anarchy_subject_name }}
  anarchy_subject_update:
    metadata:
      labels:
        state: started
    spec:
      vars:
        current_state: started
    status:
      towerJobs:
        start:
          completeTimestamp: '{{ anarchy_run_timestamp }}'
          jobStatus: successful

- name: Report action successful
  anarchy_finish_action:
    state: successful
...
