---
- name: Set failure check_status_state for {{ anarchy_subject_name }}
  when: job_action == 'status'
  anarchy_subject_update:
    skip_update_processing: true
    spec:
      vars:
        check_status_state: error
    status:
      actions:
        status:
          completeTimestamp: '{{ now_time_utc }}'
          state: error
      towerJobs:
        status:
          completeTimestamp: '{{ now_time_utc }}'
          jobStatus: error

- name: Finish action {{ anarchy_action_name }} as error
  anarchy_finish_action:
    state: error
...
