---
- name: Run deployer provision {{ anarchy_subject_name }}
  vars:
    new_subject_state: provisioning
    tower_job_template_playbook: "{{ deployer_entry_points.provision }}"
    tower_job_extra_vars: >-
      {{ vars.anarchy_subject.vars.job_vars | default({})
       | combine(vars.anarchy_governor.vars.job_vars, recursive=True)
       | combine(vars.dynamic_job_vars, recursive=True)
       | combine({
         "ACTION": "provision",
         callback_url_var: anarchy_action_callback_url,
         callback_token_var: anarchy_action_callback_token,
       }, recursive=True)
      }}
  include_tasks:
    file: check-run-tower-job.yaml

- name: Schedule check for provision of {{ anarchy_subject_name }}
  anarchy_continue_action:
    after: "{{ tower_job_check_interval }}"
