---
- name: Check if placement exists
  uri:
    headers:
      Authorization: Bearer {{ access_token }}
    url: "{{ sandbox_api_url }}/api/v1/placements/{{ uuid }}"
    method: GET
    status_code: [200, 404]
  retries: "{{ sandbox_api_retries }}"
  delay: "{{ sandbox_api_delay }}"
  register: r_get_placement
  until: >-
    r_get_placement.json.status | default('unknown') in ['success', 'error']
    or r_get_placement.json.http_code == 404

- name: Finish action {{ anarchy_action_name }} as failed
  when: r_get_placement.json.status == 'error'
  block:
  - name: Debug placement error
    debug:
      var: r_get_placement
      
  - name: Finish action {{ anarchy_action_name }} as failed
    include_tasks:
      file: handle-action-{{ anarchy_action_config_name }}-error.yaml

  - meta: end_play

# Placement found
- when: >-
    r_get_placement.status == 200
    and r_get_placement.json.resources | default([]) | length > 0
  block:
    - name: Set placement
      set_fact:
        placement: "{{ r_get_placement.json }}"

    - name: Inject vars into dynamic_job_vars
      set_fact:
        dynamic_job_vars: >-
          {{ vars.dynamic_job_vars
          | default({})
          | combine(r_get_placement.json | extract_sandboxes_vars, recursive=True) }}

    - name: Set sandbox for {{ anarchy_subject_name }}
      anarchy_subject_update:
        skip_update_processing: true
        metadata:
          labels: "{{ r_get_placement.json | extract_sandboxes_labels }}"
        spec:
          vars:
            job_vars: "{{ r_get_placement.json | extract_sandboxes_vars(creds=False) }}"
...
